format = """
\\[\
$username\
@\
$hostname\
:\
$directory\
\\] \
\\[ \
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
\\] \
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$nats\
$direnv\
$env_var\
$mise\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$netns\
$shell\
$character"""

# Inserts a blank line between shell prompts
add_newline = true

# Use the color palette
palette = "dracula"

# Define Dracula color palette
[palettes.dracula]
background = "#282a36"
current_line = "#44475a"
foreground = "#f8f8f2"
comment = "#6272a4"
cyan = "#8be9fd"
green = "#50fa7b"
orange = "#ffb86c"
pink = "#ff79c6"
purple = "#bd93f9"
red = "#ff5555"
yellow = "#f1fa8c"

[character]
success_symbol = "[\\$](green)"
error_symbol = "[\\$](red)"

[package]
# Disable the package module, hiding it from the prompt completely
disabled = true

[directory]
truncate_to_repo = false
truncation_length = 0
format = "[$path]($style)[$read_only]($read_only_style)"

[hostname]
ssh_only = false
format = "[$hostname]($style)"

[username]
show_always = true
format ="[$user]($style)"

[git_branch]
format ="[$symbol$branch(:$remote_branch)]($style) "

[git_state]
format = "\\([$state( $progress_current/$progress_total)]($style)\\) "

[git_status]
format = "([\\[$all_status$ahead_behind\\]]($style) )"

# previous non-starship prompt
# [lonnen@corey:~/.dotfiles][main:!?]
# [11:14:45] $